### ISSUE TITLE
Double clicking package does not open a window

### ISSUE THREAD

**Issue by DailenG** [we-mi/psChocoUpdateNotify#26]
When I double click on a package to view details, it TRIES to open a window but ends up but the GUI just disappears altogether

**Comment by we-mi** [comment]
Hey @DailenG,

thanks for your feedback :)

I'm aware of this issue, but never really had the time to fix this.
And I never really thought that anyone except me would use this software :D but I hope you like it

This bug was introduced when I implemented the markdown rendering of the chocolatey package description.
I currently got it working in Powershell 7, but not in Powershell 5.
I might need to do some more research on this and disable the markdown rendering completly in the meantime.

I'll try to push a testing version in the next couple of days, so you can test it if you want

**Comment by we-mi** [comment]
Hey @DailenG,

I published a new version (1.2.2) which hopefully fixed this issue.
Please see the [Readme](https://github.com/we-mi/psChocoUpdateNotify/blob/main/README.md) on how to update.

Feel free to check if this works for you and give me a short feedback, so I can close this issue.

**Comment by DailenG** [comment]
Checking this now 👍

**Comment by DailenG** [comment]
Issue has been fixed 💯
